weekly:
  - pilates
  - dance class
  - art group
  - mobility exercise class
  - v\s*x\s*club
  - toddler group|Baby and Toddler Group
  - yoga
  - circuit
  - badminton
excel:
  template: template/table-only.xlsx
