url: https://v2.hallmaster.co.uk/api/ical/GetICalStream?HallId=7609&listrooms=true&splitseries=true&onlyconfirmed=true
weekly:
  - pilates
  - dance class
  - art group
  - mobility exercise class
  - v\s*x\s*club
  - toddler group|Baby and Toddler Group
  - yoga
  - circuit
  - badminton
excel:
  template: template/table-only.xlsx
